#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

#==============================================
# BUILD APP
#==============================================
ynh_script_progression "Building app... (this will take some time and resources!)"

pushd "$install_dir/build"
	ynh_hide_warnings ynh_exec_as_app yarn install --ignore-optional
	ynh_hide_warnings ynh_exec_as_app NODE_ENV=production yarn build
	ynh_hide_warnings ynh_exec_as_app NODE_ENV=production yarn cache clean --all
popd

ynh_exec_as_app mv "$install_dir/build/build" "$install_dir/live"
ynh_safe_rm "$install_dir/build"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
